### ISSUE TITLE
Make dsplayer not crash...

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamori#169]
I've been trying to figure this out, I got it to work with local files, but idk. I might actually learn some DirectX and squash some dsplayer bugs on that side.

**Comment by bigretromike** [comment]
when dsplayer tend to crash ? can we reproduce it ?

**Comment by da3dsoul** [comment]
I can reproduce it 100% of the time.

**Comment by da3dsoul** [comment]
It flat out crashes

**Comment by bigretromike** [comment]
mind to shear the "know how" :-) ? or its more of kodi issue than nakamori

**Comment by da3dsoul** [comment]
Dunno. When I actually get Kodi to build in debug, I can get some useful info

**Comment by bigretromike** [comment]
also if its fixed in 17,then no one would care ;-)

**Comment by da3dsoul** [comment]
dsplayer is Jarvis only until someone updates it. Kodi devs don't support it.  Since it's not actively developed, it won't get fixed. As for why anyone would keep it, it's the only nice way to have filters and svp in Kodi.

**Comment by bigretromike** [comment]
oh so you are for svp ;p you fps-maniac

**Comment by da3dsoul** [comment]
Haha I'm trying it on recommendation for a user for debugging help. Mainly the upscaling

**Comment by da3dsoul** [comment]
It still crashes sometimes... I'm done with this for now. I'd like to actually get something done rather than wasting countless hours trying figure out both sides of broken code.
